config/routes.rb
Rails.application.routes.draw do
  root 'sessions#login'

  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#login'
  get '/createaccount', to: 'sessions#new'
  post '/createaccount', to: 'sessions#new'
  post '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  
  resources :person
  resources :emails
  resources :addresses
  resources :phonenumbers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :person, optional: true

    validates :street, presence: true
    validates :town, presence: true
    validates :zip_code, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
    belongs_to :person, optional: true

    validates :email_address, presence: true
end

app/models/person.rb
class Person < ApplicationRecord
    self.table_name = 'person'

    belongs_to :user, optional: true

    has_many :emails, dependent: :destroy
    has_many :addresses, dependent: :destroy
    has_many :phone_numbers, dependent: :destroy
    
    validates_associated :emails
    validates_associated :addresses
    validates_associated :phone_numbers

    validates :first_name, presence: true
    validates :last_name, presence: true
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
    belongs_to :person, optional: true

    validates :phone_number, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    has_many :person

    validates :username, presence: true
    validates :password_digest, presence: true
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def new
    @address = Address.new
  end

  def create
    @address = Address.create(params.require(:address).permit(:street, :town, :zip_code, :state, :country, :person_id))
    redirect_to person_path(@address.person)
  end

  def destroy
    @address = Address.find(params[:id])
    @person = @address.person
    @address.destroy
    redirect_to person_path(@person)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController

  def new
    @email = Email.new
  end

  def create
    @email = Email.create(params.require(:email).permit(:email_address, :comment, :person_id))
    redirect_to person_path(@email.person)
  end

  def destroy
    @email = Email.find(params[:id])
    @person = @email.person
    @email.destroy
    redirect_to person_path(@person)
  end
end

app/controllers/person_controller.rb
class PersonController < ApplicationController

  def index
    if !helpers.logged_in?
      redirect_to login_path
    end
    @people = Person.where(user: helpers.current_user)
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.create(params.require(:person).permit(:first_name, :last_name, :salutation, :middle_name, :ssn, :birthdate, :comment, :user_id))
    if @person.valid? && @person.user_id == helpers.current_user.id
      redirect_to controller: 'person', action: 'show', id: @person.id
    else
      flash[:errors] = @person.errors.full_messages
      redirect_to new_person_path
    end
  end

  def show
    if Person.find(params[:id]).user_id == helpers.current_user.id
      @person = Person.find(params[:id])
    else
      redirect_to action: "index"
    end
  end

  def edit
    if Person.find(params[:id]).user_id == helpers.current_user.id
      @person = Person.find(params[:id])
    else
      redirect_to action: "index"
    end
  end

  def update
    if Person.find(params[:id]).user_id == helpers.current_user.id
      @person = Person.find(params[:id])
      @person.update(params.require(:person).permit(:first_name, :last_name, :salutation, :middle_name, :ssn, :birthdate, :comment, :user_id))
      redirect_to person_path(@person)
    else
      redirect_to action: "index"
    end
  end

  def destroy
    if Person.find(params[:id]).user_id == helpers.current_user.id
      @person = Person.find(params[:id])
      @person.destroy
    end
    redirect_to action: "index"
  end
end

app/controllers/phonenumbers_controller.rb
class PhonenumbersController < ApplicationController
  def new
    @phonenumber = PhoneNumber.new
  end

  def create
    @phonenumber = PhoneNumber.create(params.require(:phone_number).permit(:phone_number, :comment, :person_id))
    redirect_to person_path(@phonenumber.person)
  end

  def destroy
    @phonenumber = PhoneNumber.find(params[:id])
    @person = @phonenumber.person
    @phonenumber.destroy
    redirect_to person_path(@person)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def login
        @user = User.find_by(username: params[:username])
        if !!@user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to controller: :person, action: :index
        end
    end

    def destroy
        @user = User.find_by(username: params[:username])
        if !!@user && @user.authenticate(params[:password])
            session[:user_id] = nil
            redirect_to login_path
        else
            message = "Something went wrong! Make sure your username and password were typed in correctly."
            redirect_to login_path, notice: message
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(params.require(:user).permit(:username, :password))
        if @user.save
            session[:user_id] = @user.id
            redirect_to controller: :person, action: :index
        else
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

    def logged_in?
        !!session[:user_id]
    end

    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if !!session[:user_id]
    end
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/helpers/phonenumbers_helper.rb
module PhonenumbersHelper
end

app/views/addresses/create.html.erb
<h1>Add new Address</h1>

<%= form_for @address do |f|%>
    <%= f.label :street%>
    <%= form_for%>
<%end%>

app/views/addresses/destroy.html.erb
<h1>Addresses#destroy</h1>
<p>Find me in app/views/addresses/destroy.html.erb</p>

app/views/addresses/edit.html.erb
<h1>Addresses#edit</h1>
<p>Find me in app/views/addresses/edit.html.erb</p>

app/views/addresses/index.html.erb
<h1>Addresses#index</h1>
<p>Find me in app/views/addresses/index.html.erb</p>

app/views/addresses/new.html.erb
<h1>Add new Address</h1>

* Required<br><br>

<%= form_for @address do |f|%>
    <%= f.label :street%>*
    <%= f.text_field :street%><br>
    <%= f.label :town%>*
    <%= f.text_field :town%><br>
    <%= f.label :zip_code%>*
    <%= f.text_field :zip_code%><br>
    <%= f.label :state%>
    <%= f.text_field :state%><br>
    <%= f.label :country%>
    <%= f.select :country, options_for_select([["USA"], ["UK"], ["France"]])%><br><br>
    <%= f.hidden_field :person_id, value: params[:person_id] %>
    <%= f.submit%>
<%end%>

app/views/addresses/show.html.erb
<h1>Addresses#show</h1>
<p>Find me in app/views/addresses/show.html.erb</p>

app/views/addresses/update.html.erb
<h1>Addresses#update</h1>
<p>Find me in app/views/addresses/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Address Book</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/person/create.html.erb
<h1>People#create</h1>
<p>Find me in app/views/people/create.html.erb</p>

app/views/person/destroy.html.erb
<h1>People#destroy</h1>
<p>Find me in app/views/people/destroy.html.erb</p>

app/views/person/edit.html.erb
<h1>Edit Person Form</h1>

<% if flash[:errors]%>
    <% flash[:errors].each do |error|%>
        <p style="color: red"><%= error%></p>
    <%end%>
<%end%>

* Required<br><br>

<%= form_for @person do |f|%>
    <%= f.label :salutation%>
    <%= f.select :salutation, options_for_select([["Mr."], ["Ms."], ["Mrs."]])%><br>
    <%= f.label :first_name%>*
    <%= f.text_field :first_name%><br>
    <%= f.label :middle_name%>
    <%= f.text_field :middle_name%><br>
    <%= f.label :last_name%>*   
    <%= f.text_field :last_name%><br>
    <%= f.label :ssn%>
    <%= f.number_field :ssn%><br>
    <%= f.label :birth_date%>
    <%= f.date_field :birthdate%><br>
    <%= f.label :comment%>
    <%= f.text_field :comment%><br><br>
    
    <%= f.submit%>
<%end%>

app/views/person/index.html.erb
<h1>Address Book</h1>

<%= button_to "Add New Person", new_person_path, method: :get %><br>
<ul class="list-group w-auto">
    <% @people.each do |person| %>
        <p class="mb-0 w-100 justify-content-between list-group-item list-group-item-action gap-3 py-3">
            <%= link_to person.salutation+" "+person.first_name+" "+person.last_name, person_path(person)%>
        </p>
    <% end %>
</ul>
<div class="b-example-divider"></div><br>
<div>
    <%= form_tag '/logout' do %>
        <%= submit_tag "Log Out" %>
    <% end %>
</div>

app/views/person/new.html.erb
<h1>New Person Form</h1>

<% if flash[:errors]%>
    <% flash[:errors].each do |error|%>
        <p style="color: red"><%= error%></p>
    <%end%>
<%end%>

* Required<br><br>

<%= form_for @person do |f|%>
    <%= f.label :salutation%>
    <%= f.select :salutation, options_for_select([["Mr."], ["Ms."], ["Mrs."]])%><br>
    <%= f.label :first_name%>*
    <%= f.text_field :first_name%><br>
    <%= f.label :middle_name%>
    <%= f.text_field :middle_name%><br>
    <%= f.label :last_name%>*
    <%= f.text_field :last_name%><br>
    <%= f.label :ssn%>
    <%= f.number_field :ssn%><br>
    <%= f.label :birth_date%>
    <%= f.date_field :birthdate%><br>
    <%= f.label :comment%>
    <%= f.text_field :comment%><br><br>
    <%= f.hidden_field :user_id, value: session[:user_id] %>
    
    <%= f.submit%>
<%end%>

app/views/person/show.html.erb
<h1><%= @person.salutation+" "+@person.first_name+" "+@person.last_name%>'s Contact Page</h1>

<h2><%= link_to "Back to Address Book", "/person"%></h2>

<h2>Comment</h2>
<p><%= @person.comment%></p>

<h2>Addresses</h2>
<%= button_to "Add Address", new_address_path, params: {person_id: @person.id}, method: :get%>
<ul>
    <% @person.addresses.each do |address|%>
        <li><%= address.street+", "+address.town+" "+address.zip_code %></li>
        <li><%= address.state+", "+address.country%>
        <%= button_to "Delete Address", address_path(address), method: :delete%>
    <%end%>
</ul>
<h2>Emails</h2>
<%= button_to "Add Email", new_email_path, params: {person_id: @person.id}, method: :get%>
<ul>
    <% @person.emails.each do |email|%>
        <li><%= email.email_address%> * Comment: <%= email.comment%></li>
        <%= button_to "Delete Email", email_path(email), method: :delete%>
    <%end%>
</ul>
<h2>Phone Numbers</h2>
<%= button_to "Add Phone Number", new_phonenumber_path, params: {person_id: @person.id}, method: :get%>
<ul>
    <% @person.phone_numbers.each do |number|%>
        <li><%= number.phone_number %> * Comment: <%= number.comment%></li>
        <%= button_to "Delete Number", phonenumber_path(number), method: :delete%>
    <%end%>
</ul>

<%= button_to "Edit Person", edit_person_path, method: :get%>
<%= button_to "Delete Person", person_path, method: :delete%>

app/views/person/update.html.erb
<h1>person#update</h1>
<p>Find me in app/views/person/update.html.erb</p>

app/views/phonenumbers/create.html.erb
<h1>Phonenumbers#create</h1>
<p>Find me in app/views/phonenumbers/create.html.erb</p>

app/views/phonenumbers/destroy.html.erb
<h1>Phonenumbers#destroy</h1>
<p>Find me in app/views/phonenumbers/destroy.html.erb</p>

app/views/phonenumbers/edit.html.erb
<h1>Phonenumbers#edit</h1>
<p>Find me in app/views/phonenumbers/edit.html.erb</p>

app/views/phonenumbers/index.html.erb
<h1>Phonenumbers#index</h1>
<p>Find me in app/views/phonenumbers/index.html.erb</p>

app/views/phonenumbers/new.html.erb
<h1>Add new Phone Number</h1>

* Required<br><br>

<%= form_for @phonenumber ,:url => {:action => :create, :controller => :phonenumbers} do |f| %>
    <%= f.label :phone_number%>*
    <%= f.text_field :phone_number%><br>
    <%= f.label :comment%>
    <%= f.text_field :comment%><br><br>
    <%= f.hidden_field :person_id, value: params[:person_id] %>
    <%= f.submit%>
<%end%>

app/views/phonenumbers/show.html.erb
<h1>Phonenumbers#show</h1>
<p>Find me in app/views/phonenumbers/show.html.erb</p>

app/views/phonenumbers/update.html.erb
<h1>Phonenumbers#update</h1>
<p>Find me in app/views/phonenumbers/update.html.erb</p>